In [ ]:
from google.colab import files
uploaded = files.upload()

Saving road_construction_dataset.csv to road_construction_dataset.csv

In [ ]:
import pandas as pd
df = pd.read_csv("road_construction_dataset.csv")
df.head()

,Road_Type,Road_Length_km,Road_Width_m,Road_Thickness_m,Number_of_Lanes,Soil_Type,Construction_Quality,Aggregate_Required_m3,Sand_Required_m3,Cement_Required_tonnes,Bitumen_Required_tonnes,Steel_Required_tonnes,Material_Cost,Labour_Cost,Total_Construction_Cost
0,Asphalt,14.11,6.0,0.15,2,Medium,Premium,21651.80,1117.51,279.38,768.29,0.00,84665502.9,7682895.0,92348397.9
1,Concrete,10.95,11.0,0.15,4,Medium,Standard,24391.12,9937.12,5420.25,0.00,632.36,137584012.5,14454000.0,152038012.5
2,Asphalt,6.54,7.5,0.25,2,Medium,Standard,19006.88,981.00,245.25,674.44,0.00,74323012.5,6744375.0,81067387.5
3,Asphalt,16.37,10.0,0.22,4,Medium,Standard,55821.70,2881.12,720.28,1980.77,0.00,218280854.0,19807700.0,238088554.0
4,Asphalt,13.85,10.0,0.20,4,Weak,Standard,47228.50,2216.00,554.00,1523.50,0.00,175618000.0,15235000.0,190853000.0

In [5]:
df.info()
df.columns
print("Checking null values",df.isnull().sum()) #Checking null values
print("Duplicates:",df.duplicated().sum()) #Checking duplicates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Road_Type                1000 non-null   object
 1   Road_Length_km           1000 non-null   float64
 2   Road_Width_m             1000 non-null   float64
 3   Road_Thickness_m         1000 non-null   float64
 4   Number_of_Lanes          1000 non-null   int64
 5   Soil_Type                1000 non-null   object
 6   Construction_Quality     1000 non-null   object
 7   Aggregate_Required_m3    1000 non-null   float64
 8   Sand_Required_m3         1000 non-null   float64
 9   Cement_Required_tonnes   1000 non-null   float64
 10  Bitumen_Required_tonnes  1000 non-null   float64
 11  Steel_Required_tonnes    1000 non-null   float64
 12  Material_Cost            1000 non-null   float64
 13  Labour_Cost              1000 non-null   float64
 14  Total_Construction_Cost  1000 non-null   float64
dtypes: float64(11), int64(1), object(3)
memory usage: 117.3+ KB
Checking null values Road_Type                  0
Road_Length_km             0
Road_Width_m               0
Road_Thickness_m           0
Number_of_Lanes            0
Soil_Type                  0
Construction_Quality       0
Aggregate_Required_m3      0
Sand_Required_m3           0
Cement_Required_tonnes     0
Bitumen_Required_tonnes    0
Steel_Required_tonnes      0
Material_Cost              0
Labour_Cost                0
Total_Construction_Cost    0
dtype: int64
Duplicates: 1

In [6]:
X = df[['Road_Type','Road_Length_km','Road_Width_m','Road_Thickness_m','Number_of_Lanes','Soil_Type','Construction_Quality']]
Y = df[['Aggregate_Required_m3','Sand_Required_m3','Cement_Required_tonnes','Bitumen_Required_tonnes','Steel_Required_tonnes','Material_Cost','Labour_Cost','Total_Construction_Cost']]

In [7]:
X_encoded = pd.get_dummies(X,columns=['Road_Type', 'Soil_Type', 'Construction_Quality'])

X_encoded.head()

,Road_Length_km,Road_Width_m,Road_Thickness_m,Number_of_Lanes,Road_Type_Asphalt,Road_Type_Concrete,Soil_Type_Medium,Soil_Type_Strong,Soil_Type_Weak,Construction_Quality_Premium,Construction_Quality_Standard
0,14.11,6.0,0.15,2,True,False,True,False,False,True,False
1,10.95,11.0,0.15,4,False,True,True,False,False,False,True
2,6.54,7.5,0.25,2,True,False,True,False,False,False,True
3,16.37,10.0,0.22,4,True,False,True,False,False,False,True
4,13.85,10.0,0.20,4,True,False,False,False,True,False,True

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_encoded, Y, test_size=0.2, random_state=42)

In [9]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(X_train, Y_train)

RandomForestRegressor(random_state=42)

In [11]:
y_pred = model.predict(X_test)

print(y_pred)

[[1.61078984e+04 9.53652900e+02 2.79693600e+02 ... 6.35911130e+07
  5.79902400e+06 6.93901370e+07]
 [1.53252201e+04 1.83177520e+03 8.05644200e+02 ... 6.54588242e+07
  6.21451133e+06 7.16733356e+07]
 [3.35098511e+04 1.99802260e+03 5.97076300e+02 ... 1.31622461e+08
  1.19463552e+07 1.43568816e+08]
 ...
 [1.12361466e+04 3.76203800e+03 2.02121580e+03 ... 5.89709321e+07
  6.03720313e+06 6.50081352e+07]
 [2.80694159e+04 9.84106750e+03 5.31307740e+03 ... 1.49132278e+08
  1.53192626e+07 1.64451541e+08]
 [3.79359322e+04 3.71036310e+03 1.51979450e+03 ... 1.56933800e+08
  1.46440784e+07 1.71577879e+08]]

In [14]:
import numpy as np
from sklearn.metrics import  r2_score
r2 = r2_score(Y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.9631892689677166